const mongoose = require("mongoose")
const Schema = mongoose.Schema

const UserSchema = new Schema(({
    asin:{
        type:String
    },
    attributes:{
        cellular_technology:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        version_for_country:[{
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        included_components:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        item_weight:[{
            unit:{
                type:String
            },
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        model_name:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        bullet_point:[
            {
                language_tag:{
                    tyep:String
                },
                value:{
                    type:String
                },
                marketplace_id:{
                    type:String
                }
            }
        ],
        hazmat:[{
            aspect:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        connector_type:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        item_dimensions:[{
            width:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            length:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            height:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            marketplace_id:{
                type:String
            }
        }],
        brand:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        externally_assigned_product_identifier:[{
            value:{
                type:String
            },
            type:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        target_region:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        flash_memory:[{
            installed_size:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            marketplace_id:{
                type:String
            }
        }],
        number_of_items:[{
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        item_package_dimensions:[{
            lenght:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            width:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            height:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            marketplace_id:{
                type:String
            }
        }],
        telephone_type:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        warranty_description:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        packer_contact_information:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        number_of_lithium_ion_cells:[{
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        color:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        importer_contact_information:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        item_type_name:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        item_package_weight:[{
            unit:{
                type:String
            },
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        battery:[{
            cell_composition:[{
                value:{
                    type:String
                }
            }],
            weight:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            power:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            marketplace_id:{
                type:String
            }
        }],
        manufacturer:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        digital_storage_capacity:[{
            unit:{
                type:String
            },
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        number_of_boxes:[{
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        wireless_provider:[{
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        recommended_browse_nodes:[{
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        operating_system:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        lithium_battery:[{
            energy_content:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            weight:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            packaging:[{
                value:{
                    type:String
                }
            }],
            marketplace_id:{
                type:String
            }
        }],
        memory_storage_capacity:[{
            unit:{
                type:String
            },
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        supplier_declared_dg_hz_regulation:[{
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        num_batteries:[{
            quantity:{
                type:Number
            },
            type:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        special_feature:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        display:[{
            size:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            type:[{
                language_tag:{
                    type:String
                },
                value:{
                    type:String
                }    
            }],
            marketplace_id:{
                type:String
            }
        }],
        computer_memory:[{
            size:[{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }],
            marketplace_id:{
                type:String
            }
        }],
        item_name:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        list_price:[{
            value_with_tax:{
                type:Number
            },
            currency:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        effective_still_resolution:[{
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        batteries_required:[{
            value:{
                type:Boolean
            },
            marketplace_id:{
                type:String
            }
        }],
        product_site_launch_date:[{
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        form_factor:[{
            language_tag:{
                type:String
            },
            value:{
                type:String
            },
            marketplace_id:{
                type:String
            }
        }],
        unit_count:[{
            value:{
                type:Number
            },
            marketplace_id:{
                type:String
            }
        }],
        batteries_included:[{
            value:{
                type:Boolean
            },
            marketplace_id:{
                type:String
            }
        }]
    },
    dimensions:[{
        marketplaceId:{
            type:String
        },
        item:{
            height:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            length:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            weight:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            width:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }
        },
        package:{
            height:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            length:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            weight:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            },
            width:{
                unit:{
                    type:String
                },
                value:{
                    type:Number
                }
            }
        }
    }],
    identifiers:[{
        marketplaceId:{
            type:String
        },
        identifiers:[{
            identifierType:{
                type:String
            },
            identifier:{
                type:String
            }
        }]
    }],
    images:[{
        marketplaceId:{
            type:String
        },
        images:[{
            variant:{
                type:String
            },
            link:{
                type:String
            },
            height:{
                type:Number
            },
            width:{
                type:Number
            }
        }]
    }],
    productTypes:[{
        marketplaceId:{
            type:String
        },
        productType:{
            type:String
        }
    }],
    relationships:[{
        marketplaceId:{
            type:String
        },
        relationships:[{
            parentAsins:[{
                type:String
            }],
            type:{
                type:String
            }
        }]
    }],
    salesRanks:[{
        marketplaceId:{
            type:String
        },
        classificationRanks:[{
            classificationId:{
                type:String
            },
            title:{
                type:String
            },
            link:{
                type:String
            },
            rank:{
                type:Number
            }
        }],
        displayGroupRanks:[{
            websiteDisplayGroup:{
                type:String
            },
            title:{
                type:String
            },
            link:{
                type:String
            },
            rank:{
                type:Number
            }
        }]
    }],
    summaries:[{
        marketplaceId:{
            type:String
        },
        brand:{
            type:String
        },
        browseClassification:{
            displayName:{
                type:String
            },
            classificationId:{
                type:String
            }
        },
        color:{
            type:String
        },
        itemClassification:{
            type:String
        },
        itemName:{
            type:String
        },
        manufacturer:{
            type:String
        },
        size:{
            type:String
        },
        websiteDisplayGroup:{
            type:String
        },
        websiteDisplayGroupName:{
            type:String
        }
    }]
}))

// module.exports = User = mongoose.model('User',UserSchema)